### ISSUE TITLE
Spark 3.3.0 - Abstract method error

### ISSUE THREAD

**Issue by vinodprathipati** [elastacloud/spark-excel#24]
Hi ,

I am getting an in databricks environment. I am getting abstract method error.
Spark version is: 3.3.0

Caused by: AbstractMethodError: org.apache.spark.sql.execution.datasources.v2.FilePartitionReaderFactory.options()Lorg/apache/spark/sql/catalyst/FileSourceOptions;
	at org.apache.spark.sql.execution.datasources.v2.FilePartitionReaderFactory.createReader(FilePartitionReaderFactory.scala:35)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.advanceToNextIter(DataSourceRDD.scala:84)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.hasNext(DataSourceRDD.scala:63)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:761)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:80)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:186)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:169)
	at org.apache.spark.scheduler.Task.$anonfun$run$4(Task.scala:137)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:36)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:58)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:63)

Any help is appreciated?

Vinod

**Comment by dazfuller** [comment]
@vinodprathipati which version of the Databricks runtime is this?

**Comment by vinodprathipati** [comment]
@dazfuller , yes this issue is in databricks 11.3 lts..

**Comment by dazfuller** [comment]
Thanks, and that's really useful info for helping to fix this

**Comment by vinodprathipati** [comment]
How are you planning to fix this?

**Comment by dazfuller** [comment]
At the moment I'm still trying to recreate it locally so I can fix it.

At the moment the only suggestion I could make is to switch back to a spark 3.2 runtime, but obviously only if it's achievable

**Comment by dazfuller** [comment]
It looks as though Databricks are using a patched version of Spark which includes changes in the master branch which aren't in the 3.3 support branch.

I found the referenced change in the [master branch](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/FilePartitionReaderFactory.scala) which includes this change. It was made in April 2022 but the 3.3 support branch was created in Feb 2022.

I've been looking around and it seems quite a few 3rd party data sources are having this issue.

I'll keep looking to see how this can be resolved

**Comment by dazfuller** [comment]
Just to let you know that I'm still investigating this and have a ticket open with Databricks to find a solution

**Comment by dazfuller** [comment]
Having worked with Databricks there's a patch on its way that will fix this in the 11.x and 12.x runtimes. Hopefully it should be landing sometime in January

**Comment by vinodprathipati** [comment]
Hi ,

I also worked with databricks team and they provided a custom image to experiment. It worked fine with custom image.
As you mentioned,  they are going to provide a patch some time in January.
Thanks for your feedback.

**Comment by dazfuller** [comment]
You got the custom image as well 😀

Yeah it worked great with that, so fingers crossed for the full release

**Comment by dazfuller** [comment]
Closing as resolved by Databricks
